### ISSUE TITLE
Is this "dangerous" to install still?

### ISSUE THREAD

**Issue by tiotrom** [YunoHost-Apps/invidious_ynh#10]
In ynh dashboard it says that this application is not maintained and probably won't work, but here I see it is maintained and recently updated. So, is it ok to install it? :)

**Comment by alexAubin** [comment]
Yes, the badge on the readme still says Level 0, the install miserably fails for some obscur reason because of crystal builld, cf. https://ci-apps.yunohost.org/ci/job/1367

**Comment by ericgaspar** [comment]
#11 should solve the installation problem. I changed the Crystal repository from an obsolete debian package to a newer version. Please feel free to reopen if you are still having trouble installing Invidious.
