### ISSUE TITLE
Update Failed - "Variable $admin wasn't initialized when trying to replace __ADMIN__ "

### ISSUE THREAD

**Issue by vincbic** [YunoHost-Apps/invidious_ynh#115]
### Describe the bug

Can't update Invidious to 23.03.21~ynh1 from 23.02.14~ynh1.
Warning: Variable $admin wasn't initialized when trying to replace __ADMIN__ in /var/www/invidious/config/config.yml

### Context

- Hardware: x86
- YunoHost version: 11.1.15
- Using, or trying to install package version/branch: Tried from both the master and testing branches

### Steps to reproduce

Standard application update

### Logs

Warning: Here's an extract of the logs before the crash. It might help debugging the error:
Info: DEBUG - + sed --in-place $'s\001__PATH__\001/\001g' /var/www/invidious/config/config.yml
Info: DEBUG - + test -n invidious
Info: DEBUG - + ynh_replace_string --match_string=__NAME__ --replace_string=invidious --target_file=/var/www/invidious/config/config.yml
Info: DEBUG - + sed --in-place $'s\001__NAME__\001invidious\001g' /var/www/invidious/config/config.yml
Info: DEBUG - + ynh_replace_string --match_string=__NAMETOCHANGE__ --replace_string=invidious --target_file=/var/www/invidious/config/config.yml
Info: DEBUG - + sed --in-place $'s\001__NAMETOCHANGE__\001invidious\001g' /var/www/invidious/config/config.yml
Info: DEBUG - + ynh_replace_string --match_string=__USER__ --replace_string=invidious --target_file=/var/www/invidious/config/config.yml
Info: DEBUG - + sed --in-place $'s\001__USER__\001invidious\001g' /var/www/invidious/config/config.yml
Info: DEBUG - + test -n ''
Info: DEBUG - + dpkg --compare-versions 2.0 lt 2
Info: DEBUG - + test -n ''
Info: DEBUG - ++ grep -oP '__[A-Z0-9]+?[A-Z0-9_]*?[A-Z0-9]*?__' /var/www/invidious/config/config.yml
Info: DEBUG - ++ sed 's@__\([^.]*\)__@\L\1@g'
Info: DEBUG - ++ sort --unique
Info: DEBUG - + uniques_vars=('admin' 'captcha_enabled' 'db_name' 'db_pwd' 'db_user' 'domain' 'email' 'language' 'login_enabled' 'port' 'registration_enabled')
Info: DEBUG - + local delimit=@
Info: DEBUG - + for one_var in "${uniques_vars[@]}"
Info: DEBUG - + [[ -v admin ]]
Info: DEBUG - + ynh_die '--message=Variable $admin wasn'\''t initialized when trying to replace __ADMIN__ in /var/www/invidious/config/config.yml'
Info: DEBUG - + ynh_exit_properly

**Comment by MayeulC** [comment]
Same issue here: https://paste.yunohost.org/raw/nejejibaso
