### ISSUE TITLE
Granular control of permissions between the Invidious API and Invidious APP 

### ISSUE THREAD

**Issue by vincbic** [YunoHost-Apps/invidious_ynh#116]
Is there any way to allow permission to the Invidious API to visitors and Invidious APP to only certains users? 
So an invidious instance could be added to Yattee without making Invidious fully available to all?

**Comment by ericgaspar** [comment]
The permissions you propose are already there:
https://github.com/YunoHost-Apps/invidious_ynh/blob/f8e569135e08f69dcd3fe1a28ecef8d26c2feac9/manifest.toml#L58-L64
