### ISSUE TITLE
Invidious upgrade failed with script error

### ISSUE THREAD

**Issue by chbmeyer** [YunoHost-Apps/invidious_ynh#156]
Hello there,

I'm trying to upgrade Invidious from `24.02.12~ynh1` to `24.03.29~ynh1` on a YunoHost 11.2.11.3 (stable).

It fails with a script error caused by the wrong variable type (if I understand correctly):
```Error: expected argument #2 to 'Hash(Symbol, Float64 | Nil)#[]=' to be (Float64 | Nil), not (Time::Span | Nil)```.

Full log is https://paste.yunohost.org/raw/oluxomoxec

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.11.3 (stable)
- I have access to my server: *Through SSH* | *through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: upgrade Invidious from `24.02.12~ynh1` to `24.03.29~ynh1`

**Comment by rhetenor** [comment]
Tried to install insidious with a similar configuration and ran into the same problem when setting up the source files, although the install script has a bit longer backtrace, maybe it's helpful.

https://paste.yunohost.org/raw/ejanapugah

**Comment by chbmeyer** [comment]
Invidious `24.04.28~ynh1` solved this issue for me.
Update went without problems.
So I think I can close this issue.
