### ISSUE TITLE
Channels are not updating properly

### ISSUE THREAD

**Issue by vincbic** [YunoHost-Apps/invidious_ynh#16]
**Describe the bug:**
Channels are not updating properly. Visiting a channel results in the following error:
"Title: `unexpected token '' at 1:1 (JSON::ParseException)`" 
This seems to be resolved on Invidious main repository with #1849. 
How to force invidious to rebuild on Yunohost? 

**Versions**
Hardware: x86 VPS
YunoHost version:  4.1.7.3
I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen
Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
Using, or trying to install package version/branch: 0.20.1~ynh6

**Comment by ericgaspar** [comment]
You can force upgrade Invidious with `sudo yunohost app upgrade invidious -u https://github.com/YunoHost-Apps/invidious_ynh --force ` it will git clone upstream master branch.

**Comment by vincbic** [comment]
Perfect, thank you, it worked.
