### ISSUE TITLE
config.yml changed after upgrade

### ISSUE THREAD

**Issue by TROMsite** [YunoHost-Apps/invidious_ynh#21]
Should it be a better idea to not change the config.yml when upgrading? That's the place we, admins, use to config the instance and if an upgrade changes the file, we lose all of the configs.

**Comment by ericgaspar** [comment]
Manually-modified files should have been automatically backuped inside `/home/yunohost.conf/backup/` before they get replaced.
But I got your point of this behaviour not being admin friendly. This should be corrected with d5a8c8d

**Comment by TROMsite** [comment]
Yup I could find the backup but is good not to change that config file ;)

**Comment by TROMsite** [comment]
Thanks for https://github.com/YunoHost-Apps/invidious_ynh/commit/d5a8c8d13b59087c580692d9565e228f392f9195
