### ISSUE TITLE
Crystal version conflict

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/invidious_ynh#26]
The `crystal` package version is old. `apt update` proposes this version instead: `crystal/all 1.0.0-1 amd64 [upgradable from: 0.36.1-1]` (related to https://github.com/YunoHost-Apps/invidious_ynh/issues/19#issuecomment-809608267 ?)

But if you update to that version, you can no longer install invidious (sorry, I forgot to save the logs…) because of a conflict. This happens for instance if you install bibliogram (hence crystal package), then `apt upgrade`, then invidious.

Should that package be marked as "onhold" or something like that ?

**Comment by TROMsite** [comment]
Ops I upgraded Crystal today too. Had no idea it will impact Invidious. Luckily I had invidious installed already and all seems to work fine with the latest Crystal. So then it means Invidious can use that version of Crystal. Maybe the dev should use that.

**Comment by tigresansrayure** [comment]
Hello,
Same issue as @lars1134 here too, unable to install because of the 'crystal' version related error.

**Comment by lapineige** [comment]
Reported on the forum too https://forum.yunohost.org/t/unable-to-install-invidious/15625/2

**Comment by ericgaspar** [comment]
Sooo ... I made another attempt to install Crystal from the GitHub repository. Can anyone test from the test branch ... 
`sudo yunohost app install https://github.com/YunoHost-Apps/invidious_ynh/tree/testing`
