### ISSUE TITLE
Faster updates to keep it functional

### ISSUE THREAD

**Issue by TROMsite** [YunoHost-Apps/invidious_ynh#27]
I just want to suggest, if possible, to update invidious faster for ynh else it becomes very non-functional. Youtube changes how their HTML is produced/generated and breaks invidious very often. The upstream seems to fix such issues quite fast, but ynh takes a long time to push the changes. I totally understand this may be difficult, but I am just pointing it out. We provide our own instance and we saw how fast it broke. 

Therefore, if possible, would be great to push updates faster for this package. Thank you for your work!

**Comment by ericgaspar** [comment]
Invidious_ynh is installed with a git clone so if you install Invidious now you should get the latest available changes.
What bother me is that upstream app is not yet compatible with Crystal 1.0.0. And the way rystal is installed now seems broken (this issue should be solved when PR #2005, #1934, #1933 are merged upstream)

**Comment by TROMsite** [comment]
Aha I see. Thanks. But isn't it a way then, to either force reinstall so it picks up the latest updates, or for you to change the versioning number so that the system sees it as an update and all of us, admins, to update our invidious instances?

**Comment by ericgaspar** [comment]
You upgrade with `--force` option
`sudo yunohost app upgrade invidious -u https://github.com/YunoHost-Apps/invidious_ynh/tree/testing --force`

**Comment by TROMsite** [comment]
Thanks a lot. Works fine now. Do you think it is better to change the versioning of this package so that it forces people to upgrade and fix invidious from time to time?

**Comment by ericgaspar** [comment]
Yes, every time an update is pushed to master the version number changes in order to trigger an upgrade. as of today it is `0.20.1~ynh8` (the versioning number is stuck to 0.20.1 ... 8 is the number of iteration for this ynh package)

**Comment by TROMsite** [comment]
Ok. Thanks!
