### ISSUE TITLE
Add job to restart invidious periodically 

### ISSUE THREAD

**Issue by ghost** [YunoHost-Apps/invidious_ynh#29]
Hi,

According to the Invidious [Installation Guide](https://github.com/iv-org/documentation/blob/master/Installation.md) :
`Because of various issues Invidious must be restarted often, at least once a day, ideally every hours.`

Maybe the Yunohost install script could add an hourly cron job to restart invidious ?

Bonne journée

**Comment by ericgaspar** [comment]
I don't know if it's the best way but you can restart the app with systemd : add to `/etc/systemd/system/invidious.service` this line `RuntimeMaxSec=86400` in `[service]` section (after `restart=alwats`). This should restart the app every 24 hours. You can set it to your needs. 

... Or you can also add a service timer 
```
# /etc/systemd/system/invidious.timer
[Unit]
Description=Lance Invidious toutes les heures

[Timer]
OnCalendar=hourly

[Install]
WantedBy=timers.target
```
(don't forget to set `Type=oneshot` in `/etc/systemd/system/invidious.service`.

You are welcome to push a PR ifany of this is working.

**Comment by TROMsite** [comment]
> I don't know if it's the best way but you can restart the app with systemd : add to /etc/systemd/system/invidious.service this line RuntimeMaxSec=86400 in [service] section (after restart=alwats). This should restart the app every 24 hours. You can set it to your needs.

I've tried that but it doesn't seem to do the job. I restarted invidious after I did the change but the same. Should I reboot the server for this to take effect?
