### ISSUE TITLE
Embedding isn't allowed

### ISSUE THREAD

**Issue by georgelemental** [YunoHost-Apps/invidious_ynh#3]
**Describe the bug**
When Invidious is installed through this Yunohost app, `/embed/` links are served with an `X-Frame-Options SAMEORIGIN` header that prevents embedding. This breaks the functionality of extensions like https://github.com/SimonBrazell/privacy-redirect that replace YouTube embed links with Invidious links.

**Versions**
- Hardware: x86 Desktop
- YunoHost version: 4.1.4.4
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch:  0.20.1~ynh2

**Expected behavior**
Invidious pages under `/embed/` are served without an `X-Frame-Options SAMEORIGIN` header and can be embedded in other sites.

**Comment by alexAubin** [comment]
Indeed, we should probably add X-Frame-Options ALLOWALL to nginx.conf just like [here](https://github.com/YunoHost-Apps/etherpad_mypads_ynh/blob/testing/conf/nginx.conf#L13)

**Comment by georgelemental** [comment]
Following the recent update, `/embed/' links can be embedded but they also give a 404.
