### ISSUE TITLE
Outdated deb repository for crystal blocks upgrade of the yunohost instance

### ISSUE THREAD

**Issue by Qprq** [YunoHost-Apps/invidious_ynh#30]
**Describe the bug**
The crystal repository as set in the install script no longer exists (the service hosting it is closing down). Updating the repos won't work (apt update stops on a 403 Forbidden error).

**Versions**
- Hardware: *VPS bought online*
- YunoHost version: 4.1.8
- I have access to my server: *Through SSH & through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 0.20.1~ynh8
- If upgrading, current package version: 0.20.1~ynh8

**To Reproduce**
Try to upgrade the server from CLI or webadmin

**Expected behavior**
Successfull upgrade of the server

**Logs**
Impossible de mettre à jour le cache APT (gestionnaire de paquets Debian). Voici un extrait du fichier sources.list qui pourrait vous aider à identifier les lignes problématiques :
sources.list:deb http://debian.proxad.net/debian buster main
sources.list:deb-src http://debian.proxad.net/debian buster main
sources.list:deb http://security.debian.org/ buster/updates main
sources.list:deb-src http://security.debian.org/ buster/updates main
sources.list.d/yunohost.list:deb http://forge.yunohost.org/debian/ buster stable
sources.list.d/extra_php_version.list:deb https://packages.sury.org/php/ buster main
**sources.list.d/crystal.list:deb https://dl.bintray.com/crystal/deb all stable**
sources.list.d/onlyoffice.list:deb http://download.onlyoffice.com/repo/debian squeeze main

E: The repository 'https://dl.bintray.com/crystal/deb all InRelease' is no longer signed.

E: Failed to fetch https://dl.bintray.com/crystal/deb/dists/all/InRelease 403 Forbidden

**Fix**
Current repos for crystal can be found here : 
https://software.opensuse.org/download.html?project=devel%3Alanguages%3Acrystal&package=crystal

**Comment by straight-shoota** [comment]
The bintray repositories are no longer available. Crystal's distribution packages are now hosted
on the Open Build Service, see https://crystal-lang.org/2021/04/30/new-apt-and-rpm-repositories.html

/cc https://github.com/crystal-lang/crystal-website/pull/138

**Comment by straight-shoota** [comment]
If possible in any way, I would suggest to install a pre-compiled binary of invidious, instead of building it locally. Not sure if that's available, though.

**Comment by TROMsite** [comment]
True. I cannot upgrade:
```
Warning: E: Version '0.36*' for 'crystal' was not found
Warning: [Error] Upgrade failed.
```

**Comment by TROMsite** [comment]
Also, this package cannot install as fresh new due to the same issue. Even after removing crystal. So it needs to be fixed, else it is a non-working package. Of course, we should keep calm and nice, the developers should not be under pressure. Thank you for your work!

**Comment by ericgaspar** [comment]
I have set Invivious as not working until the  upstream package gets updated to use the last version of Crystal.

**Comment by ericgaspar** [comment]
Sooo ... I made another attempt to install Crystal from the GitHub repository. Can anyone test from the test branch ... 
`sudo yunohost app install https://github.com/YunoHost-Apps/invidious_ynh/tree/testing`

sorry to copy/pasta but it is the same issue as #19 #26 #30 #34

**Comment by zamentur** [comment]
https://github.com/YunoHost/issues/issues/1792
