### ISSUE TITLE
Live videos doesn't works on my instance

### ISSUE THREAD

**Issue by dejalavidavolar** [YunoHost-Apps/invidious_ynh#31]
Hello, I hope you are well. My instance of invidious (https://notyoutube.org) is working fine, except that it does not play the live videos.

Is anyone else experiencing this error?

Regards.

**Comment by saebaryo-xyz** [comment]
Yes, I've just noticed that.
Did you solve it by any chance ?

**Comment by ericgaspar** [comment]
#122 should fix the issue
