### ISSUE TITLE
Update invidious 

### ISSUE THREAD

**Issue by RouterCFW** [YunoHost-Apps/invidious_ynh#34]
Are you guys still going to update invidious ?

**Comment by ericgaspar** [comment]
I have set Invivious as not working until the upstream package gets updated to use the last version of Crystal.

**Comment by ericgaspar** [comment]
Sooo ... I made another attempt to install Crystal from the GitHub repository. Can anyone test from the test branch ... 
`sudo yunohost app install https://github.com/YunoHost-Apps/invidious_ynh/tree/testing`

sorry to copy/pasta but it is the same issue as #19 #26 #30 #34

**Comment by RouterCFW** [comment]
> Sooo ... I made another attempt to install Crystal from the GitHub repository. Can anyone test from the test branch ...
> `sudo yunohost app install https://github.com/YunoHost-Apps/invidious_ynh/tree/testing`
> 
> sorry to copy/pasta but it is the same issue as #19 #26 #30 #34

Just tested and it works :)
