### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by RouterCFW** [YunoHost-Apps/invidious_ynh#37]
So i wanted to do a fresh install and tried and now it doesn’t work here is the paste log https://paste.yunohost.org/raw/arunoyogid

**Comment by ericgaspar** [comment]
ok, upstream is now using Crystal 1.0. The issue should be fixed on the testing branch.

**Comment by RouterCFW** [comment]
> ok, upstream is now using Crystal 1.0. The issue should be fixed on the testing branch.

Thank you so much :)

**Comment by RouterCFW** [comment]
Tested and working

**Comment by ericgaspar** [comment]
Okay. Thank you for testing. I still have an error on CI tests when upgrading from the previous version ...
