### ISSUE TITLE
installation stops with the error "crystal build $final_path/src/invidious.cr --release_"

### ISSUE THREAD

**Issue by finster-** [YunoHost-Apps/invidious_ynh#41]
### Describe the bug

The installation stops with the error 
_./install: line 130: 19613 Killed                  crystal build $final_path/src/invidious.cr --release_

### Context
- VPS

### Steps to reproduce

- yunohost app install https://github.com/YunoHost-Apps/invidious_ynh

### Expected behavior

...

### Logs

*https://paste.yunohost.org/raw/acobuniyuw*

**Comment by ericgaspar** [comment]
Maybe a RAM problem. How much RAM does your VPS have? Invidious needs more than 2GB of RAM to build ...

**Comment by finster-** [comment]
Okay, that's the problem. It has only 2 GB RAM. Thanks for the package anyways!
