### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/invidious_ynh#49]
### Describe the bug

Upgrade fails

### Context

- Hardware: desktop pc
- YunoHost version: 4.2.6.1
- I have access to my server: Full
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: script in background that prevents regular wiping of dnsmasq conf file.
- Using, or trying to install package version/branch:
- If upgrading, current package version: 2021.05.09-62e9e9a

### Steps to reproduce

    ```sh
    sudo yunohost app upgrade
    ```

### Expected behavior

App upgrade

### Logs

https://paste.yunohost.org/raw/modamafude

**Comment by ericgaspar** [comment]
Can you try to upgrade from testing?
`sudo yunohost app upgrade invidious -u https://github.com/YunoHost-Apps/invidious_ynh/tree/testing`

**Comment by stemy2** [comment]
It worked !
