### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/invidious_ynh#5]
**Describe the bug**
Installation failed

**Versions**
- Hardware: Desktop PC
- YunoHost version: 4.1.6
- I have access to my server: Full
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: master
**To Reproduce**
*Steps to reproduce the behavior.*
- *If you performed a command from the CLI, the command itself is enough. For example:*

`sudo yunohost app install invidious`

**Expected behavior**
Installation success

**Logs**
https://paste.yunohost.org/raw/ibahoqobul

**Comment by tiotrom** [comment]
Same for me https://paste.yunohost.org/raw/memuzalaco

**Comment by ericgaspar** [comment]
#11 should solve the installation problem. I changed the Crystal repository from an obsolete debian package to a newer version. Please feel free to reopen if you are still having trouble installing Invidious.

**Comment by stemy2** [comment]
You can reopen the issue, it keeps failing.

https://paste.yunohost.org/raw/esegesokap

**Comment by ericgaspar** [comment]
Are you trying from the web admin? If so it may not be fully updated with master branch. Try in CLI `sudo yunohost app install https://github.com/YunoHost-Apps/invidious_ynh`

**Comment by ericgaspar** [comment]
Sooo any success?

**Comment by stemy2** [comment]
> Sooo any success?

Indeed !
