### ISSUE TITLE
Please change the versioning often, else invidious will stop working.

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/invidious_ynh#52]
Invidious needs a lot of fixing and the main repo is very often updated. If you simply change the yunohost package version you can keep up with the updates since this package simply pulls the files form the main invidious git right?
I have to always do the upgrade manually with ` sudo NO_BACKUP_UPGRADE=1 yunohost app upgrade invidious --force  `

If you tell me how I can do this myself, I can help you out to keep this package updated.

If I do not understand how this works, I am sorry, but from my tests forcing an upgrade as stated above, upgrades to the latest invidious form the main repo. And this is the difference between invidious working and not.

**Comment by ericgaspar** [comment]
The upgrade mecanism wasn't satisfying as the package could break at any time. We are now upgrading to a specific commit.
You are welcome to contribute to upgrade the package, there are two files to change:
https://github.com/YunoHost-Apps/invidious_ynh/blob/6b89406ab8c95510758353ecec07edc3097afb39/scripts/_common.sh#L7
https://github.com/YunoHost-Apps/invidious_ynh/blob/6b89406ab8c95510758353ecec07edc3097afb39/manifest.json#L9
Thank you for your help!

**Comment by tio-trom** [comment]
Ok a question. When I force upgrade it seems to ignore the 5c76cdaad9da2330311e78fc4e451c40e88a9598 commit and pulls the latest. I did that 2 days ago and I could check and it pulled the latest commit from that day. So I want to make sure this works or not. 

Actually another one: how do you go about versioning? Where are those numbers coming from? How do you bump from one version to another when it comes to simply be a change in versioning that will make all ynh users force upgrade to the latest Invidious github? 

Ok I asked more questions but once I understand I can help with keeping it updated in regards to versioning.
