### ISSUE TITLE
The current build says  2021.08.21-0db23f92

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/invidious_ynh#61]
Is this an old build despite the yunohost labeling? I just installed it and it says "Current version: 2021.08.21-0db23f92 @ master ". Here https://ytb.trom.tf/

**Comment by tio-trom** [comment]
Yes the Invidious Yunohost package is really not working. Should be labeled as such until they find a way to fix it. I've been in close contact with the Invidious developers over the past months trying to understand where the issue is, and basically it seems to be an issue with the Yunohost package....

**Comment by ericgaspar** [comment]
please reopen if needed
